### ISSUE TITLE
Dark Mode bugs

### ISSUE THREAD

**Issue by wazowski78** [Shubham0812/Animatify-ios#1]
Hi Shubham, as I said yesterday in Instagram I did check your repo and this is my first contribution, right?

First, very good jo dude! Very clean code and very good structured. It is easy to follow.

Now, I have found that the code works fine in light mode, but dark mode breaks font color in 'Tutorials' section, the view goes black and the font color doesn't change.

See you!

**Comment by Shubham0812** [comment]
Thanks, I am glad to hear that.
That's a good find, I'll fix it 😄👍

**Comment by Shubham0812** [comment]
Fixed :D
