### ISSUE TITLE
Feature- Customizable Toast Component

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Animatify-ios#18]
## Idea/feature:
Give the user a toast component, that they can use to display various kinds of messages.

## Feature Requirements
Customizable toast view component with support for both dark and light themes.

There are 3 types of toasts that your component should support - Success, Info & Warning.
For each type of toast the user will pass an additional type specifying the theme of toast - Light or Dark.
The toast should appear on top on other views on the screen.

The user should also be able to pass the duration for the toast.

Examples- 

#### Success toast with Light Theme
![green](https://user-images.githubusercontent.com/19903539/95205269-c56ace00-0802-11eb-8d26-9a23f5224d95.png)

#### Info toast with Light Theme
![infi](https://user-images.githubusercontent.com/19903539/95205507-14186800-0803-11eb-91d9-cb3072022063.png)

#### Warning toast with Dark Theme
![failure](https://user-images.githubusercontent.com/19903539/95205515-15e22b80-0803-11eb-97d7-8d52939b638a.png)

## Specification 
Create a custom class under the Components group named ToastView. ( Creating a custom view/Xib preferably against programmatic UI.)

The toast should occupy 70-80% of the device's width, figure out a value that looks the best on most of the devices.
It should be 

#### Icons for Toasts (SFSymbols)
1. Success - checkmark.circle.fill
2. Info - info.circle.fill
3. Warning - xmark.circle.fill

I've used SF Pro for the mockups, the project already has Raleway and Montserrat, I'd recommend to use that.
The user should also be able to pass the Title & the message for the toast in the ToastView initializer.

Enum for **ToastMode**, make another enum for **ToastTheme** that returns the color based on light/dark & ToastMode.
```
enum ToastMode {
    case success
    case info
    case warning
}
```
## How should I start working on it?
1. Mention in the comments that I'll be working on this task. (I'll assign the task to you, this helps in letting other contributors know that the task has been taken)
2. Do read the [Contribution.md](https://github.com/Shubham0812/Animatify-ios/blob/master/CONTRIBUTING.md) document before starting this task.
3. Fork from the dev branch.

## What to do when you complete the task?
Once you're done do a quick pull from the dev branch and Raise a PR and link this issue in that.
I'll review it as soon as I can, and drop my inputs on the same.

**Comment by K4stor** [comment]
Just to get it right, the toast should be above all other views, and disappear after a certain time, correct ?

**Comment by Shubham0812** [comment]
Yes, that's correct. I somehow forgot to mention that, the toast should appear on top of other views & it should fade in and fade out in the duration provided by the user in the initializer.

**Comment by K4stor** [comment]
Could it be useful to add userinteraction ? Like a closure that is called when the user taps on the toast ?

**Comment by Shubham0812** [comment]
No, not for this. Toasts are usually without a user-interaction. 

Let me think about it a bit, we can maybe have another component where we can add interactivity.

**Comment by K4stor** [comment]
Ok will code it tonight.

BTW You could have a snackbar that has a text and a button in the righthand side 
https://material-ui.com/de/components/snackbars/

**Comment by Shubham0812** [comment]
@K4stor cool, I'm assigning it to you.

And yes, something like that, I'll create an Issue. :D

**Comment by K4stor** [comment]
Done

**Comment by Shubham0812** [comment]
@K4stor do change the branch the target branch to dev.

**Comment by K4stor** [comment]
oops :-D

**Comment by Shubham0812** [comment]
Good job, accepted the merge :D 👍🏻
