### ISSUE TITLE
Feature: Create a Tutorial VC for showcasing the ToastViews

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Animatify-ios#25]
## Idea/feature:
Create a VC under Tutorials, to showcase the ToastViews.

## Feature Requirements
Create a new ViewController and it's view in Tutorials.storyboard, try to keep the UI simple.

Create separate buttons to invoke the various types of Toasts. More detail on the Toast can be found in #18.

## Specification
Create the ViewController under the Tutorials group. ( Creating a custom view/Xib preferably against programmatic UI.)

At minimum, the VC should have a Title( use the same font and size as in the Animating Tableview cells), a description and buttons, feel free to use your creativity to make it interesting. 

## How should I start working on it?
Mention in the comments that I'll be working on this task. (I'll assign the task to you, this helps in letting other contributors know that the task has been taken)

Do read the Contribution.md document before starting this task and don't forget to fork from the dev branch.

## What to do when you complete the task?
Once you're done do a quick pull from the dev branch and Raise a PR and link this issue in that.
I'll review it as soon as I can, and drop my inputs on the same.

**Comment by K4stor** [comment]
Hi, I'd like to work on this.

**Comment by Shubham0812** [comment]
@K4stor Cool, I'm assigning it to you :D

**Comment by camiloibarrayepes** [comment]
it's available to send a pr?

**Comment by camiloibarrayepes** [comment]
I would like to work on it, even if it is not assigned to me

**Comment by K4stor** [comment]
> I would like to work on it, even if it is not assigned to me

Why I am on it already will be done tonight .

**Comment by K4stor** [comment]
Ok done -> PR.
