### ISSUE TITLE
Bug: Fix the Buttons clipping issue for iPads

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Animatify-ios#26]
## Insights/Suggestions:
Fix the buttons clipping in Floating Button Animations which is under Tutorials group.

## Requirements
The buttons on the right side of the ButtonsVC, is getting clipped, you have to fix that.

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-10-16 at 12 21 15](https://user-images.githubusercontent.com/19903539/96222903-b0ccc980-0faa-11eb-9ac4-208e487a0208.png)

## Specification
Check out the ButtonsViewController that is under Tutorials group.
The buttons are added programmatically who you have to fix it there itself.

## How should I start working on it?
Mention in the comments that I'll be working on this task. (I'll assign the task to you, this helps in letting other contributors know that the task has been taken)

Do read the Contribution.md document before starting this task and don't forget to fork from the dev branch.

## What to do when you complete the task?
Once you're done do a quick pull from the dev branch and Raise a PR and link this issue in that.
I'll review it as soon as I can, and drop my inputs on the same.

**Comment by Pancreax** [comment]
@Shubham0812  Hi! I would like to work on this issue!

**Comment by Shubham0812** [comment]
Alright, I'm assigning it to you :D
