### ISSUE TITLE
Feature: Add the capability to open Github Repository inside app

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Animatify-ios#28]
## Idea/feature:
Allow the User to open the repository inside the app for a quick glance.

## Feature Requirements
1. Create a More ViewController to show various options/choices present in the app (As of now there will be only 1 option).
2. Create a new ViewController and add the capability to open this GitHub repository inside the Animatify app.

![feature-SafariView1](https://user-images.githubusercontent.com/19903539/96235685-b3ceb680-0fb8-11eb-947b-5ea307561283.png)  ![feature-SafariView2](https://user-images.githubusercontent.com/19903539/96235585-9d285f80-0fb8-11eb-8c55-d16f3576a2c8.png)

## Feature Specification
Create both the ViewControllers in the Home group. MoreVC will have a tableView and on pressing the various options their associated VC's should open. 

Add the new TableViewCell for the MoreVC under the **Cells** group.

Once this is done, Create another ViewController that opens this repository inside the app. I'd recommend using the **SafariViewController** instead of WebViews.

Display this link- https://github.com/Shubham0812/Animatify-ios/

P.S. - Don't forget to add the button in the HomeViewController to enter the MoreViewController.
 
## How should I start working on it?

This task has a dependency on #29, if that one isn't completed, I'd like you to take that one first :)

Mention in the comments that I'll be working on this task. (I'll assign the task to you, this helps in letting other contributors know that the task has been taken)

Do read the Contribution.md document before starting this task and don't forget to fork from the dev branch.

## What to do when you complete the task?
Once you're done do a quick pull from the dev branch and Raise a PR and link this issue in that.
I'll review it as soon as I can, and drop my inputs on the same.

**Comment by fredmurakawa** [comment]
I'll be working on this task.

**Comment by Shubham0812** [comment]
Sure @fredmurakawa , I'm assigning it to you :D

**Comment by fredmurakawa** [comment]
How does the back button in MoreVC should look like @Shubham0812 ?

**Comment by Shubham0812** [comment]
@fredmurakawa Let's make it as a modal presentation :)

**Comment by fredmurakawa** [comment]
Ok!
