### ISSUE TITLE
Feature: Create a Code Symbol View

### ISSUE THREAD

**Issue by Shubham0812** [Shubham0812/Animatify-ios#29]
## Idea/feature:
Create a CodeSymbol using the existing SF Symbols

## Feature Requirements
Create a new CodeSymbolView component, that can be used anywhere in the project.

![code_symbol](https://user-images.githubusercontent.com/19903539/96238708-66ecdf00-0fbc-11eb-8fec-83f3dcb6a195.png)

## Feature Specification
Create a custom class CodeSymbolView under the components Group.
Use these SFSymbols - chevron.left & chevron.right

The class should have an initializer that takes the color for the symbols as well an UIImage.SymbolConfiguration object.
(UIImage.SymbolConfiguration can be used to provide the font, size and weight of the symbol)

You can create it programmatically, or use a XiB, it's upto you.

P.S.- Just create a View that contains both the symbols, don't add the borders like I've done in the image asset above.

## How should I start working on it?
Mention in the comments that I'll be working on this task. (I'll assign the task to you, this helps in letting other contributors know that the task has been taken)

Do read the Contribution.md document before starting this task and don't forget to fork from the dev branch.

## What to do when you complete the task?
Once you're done do a quick pull from the dev branch and Raise a PR and link this issue in that.
I'll review it as soon as I can, and drop my inputs on the same.

**Comment by fredmurakawa** [comment]
I´ll be working on this

**Comment by Shubham0812** [comment]
Sure @fredmurakawa , I'm assigning it to you :D
